### ISSUE TITLE
Question about increasing binary version of components

### ISSUE THREAD

**Issue by kate-goldenring** [rylev/component-book#3]
The book states, "0c 00 is the binary version. Before the component model is standardized this will keep increasing (to ensure that it's easy to coordinate which pre-standard version the binary is). This will eventually be 01 00 when the standard is finalized."However, 0c 00 is greater than 01 00. Should this be, "This will eventually be 10 00"?

**Comment by rylev** [comment]
I believe that it will be "01 00". [Here's where this information comes from](https://github.com/WebAssembly/component-model/blob/79c0614c55b06896af3349f5dadf644fb077922b/design/mvp/Binary.md?plain=1#L45). I'll add a link to this.
